# Generated by Django 4.2.1 on 2023-06-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsapp', '0002_pet_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='animal_type',
            field=models.CharField(choices=[('d', 'dog'), ('c', 'cat')], default='NA', max_length=30),
        ),
    ]
